# Generated by Django 4.2.20 on 2025-05-11 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('seller_type', models.CharField(max_length=11)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sellers',
                'managed': False,
            },
        ),
    ]
