# Generated by Django 5.2 on 2025-05-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'images',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
