# Generated by Django 4.2.20 on 2025-05-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyimage_alter_property_options_delete_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='properties',
        ),
    ]
