# Generated by Django 4.2.21 on 2025-05-12 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0003_alter_property_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOffer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('offer_amount', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
    ]
