# Generated by Django 4.2.21 on 2025-05-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_purchaseoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseoffer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
