# Generated by Django 5.2 on 2025-05-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_purchaseoffer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseoffer',
            options={'managed': False},
        ),
    ]
