# Generated by Django 5.2 on 2025-05-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_purchaseoffer_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchaseoffer',
            table='purchase_offers',
        ),
    ]
